### ISSUE TITLE
My Books tab error

### ISSUE THREAD

**Issue by essramos** [GoogleCloudPlatform/getting-started-python#127]
I have followed instructions under 4-auth folder. 
When clicking My Books tab, I am having this error 

An internal error occurred:
`'profile'`
See logs for full stacktrace.

Tried @jonparrott  suggestion on this issue:
https://github.com/GoogleCloudPlatform/getting-started-python/issues/95

But gave me this error : 
An internal error occurred:
`'Request' object has no attribute 'session'`
See logs for full stacktrace.

**Comment by jonparrott** [comment]
Hi @essramos! That log statement should be `logging.info(session)`

**Comment by essramos** [comment]
Hi @jonparrott, I figured it was `logging.info(session)`, I tried that, and there is no "profile" key from the session.

**Comment by essramos** [comment]
here is the detail of the session. I just left some of the keys blank. 

```
{
  "google_oauth2_credentials": {
    "token_response": {
      "expires_in": 3600,
      "id_token": "",
      "token_type" : "Bearer",
      "access_token": ""
    },
    "scopes": [
      "profile",
      "email"
    ],
    "_class": "OAuth2Credentials",
    "revoke_uri": "https://accounts.google.com/o/oauth2/revoke",
    "token_info_uri": "https://www.googleapis.com/oauth2/v3/toke\r\nninfo",
    "token_uri": "https://www.googleapis.com/oauth2/v4/token",
    "refresh_token": null,
    "invalid": false,
    "id_token": {
      "azp": "",
      "exp": 1497581985,
      "email": "",
      "sub": "113869672794459914014",
      "at_hash": "",
      "iat": 1497578385,
      "picture": "https://lh4.googleusercontent.com/-sdrufhE2XEA/AAAAAAAAAAI/AAAAAAAAAGI/v9s7xTQwoxw/s96-c/photo.jpg",
      "given_name": "Ella Sh\r\nerilyn",
      "aud": "",
      "name": "Ella Sherilyn Ramos",
      "iss": "https://accounts.google.com",
      "family_name": "Ramos",
      "locale": "en",
      "email_verified": true
    },
    "user_agent": null,
    "client_secret": "",
    "access_token": "",
    "token_expiry": "2017-06-16T02:59:45Z",
    "_modu\r\nle": "oauth2client.client",
    "client_id": ""
  },
  "google_oauth2_csrf_token": ""
}
```

**Comment by jonparrott** [comment]
@essramos just to be sure, can you add a logging statement to [_request_user_info](https://github.com/GoogleCloudPlatform/getting-started-python/blob/master/4-auth/bookshelf/__init__.py#L108) to log out the session at the end of the function and see if `profile` is in there?

I also *think* this is the might same issue that @waprin and I observed a while back - the session is becoming too large to fit into a cookie, so chrome is ignoring the cookie.

**Comment by essramos** [comment]
Hi @jonparrott , by logging out the session on `_request_user_info` you mean I should call the end point `'/logout'`?

**Comment by essramos** [comment]
This error came up as well :

```
ERROR in __init__: Error while obtaining user profile: {'transfer-encoding': 'chunked', 'date': 'Tue, 20 Jun 2017 03:11:32 GMT', 'content
-length': '963', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Tue, 20 Jun 2017 03:11:32 GMT', 'server': 'GSE', 'x-xss-protection': '1; mode=block', 'status': '403', '-conte
nt-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', 'cache-control': 'private, max-age=0', 'vary': 'Origin, X-Origin'}
```

**Comment by jonparrott** [comment]
Interesting - a 403 means we made an unauthenticated request. Can you try logging `credentials.__dict__` as well? Please elide the access and refresh tokens.

**Comment by essramos** [comment]
On `_request_user_info`, I tried to print the `content` instead of `resp `when catching the error. This is what I got. 

```
ERROR in __init__: Error while obtaining user profile: b'{\n "error": {\n  "errors": [\n   {\n    "domain": "usageLimits",\n    "reason": "accessNotConfigured",\n    "messa
ge": "Access Not Configured. Google+ API has not been used in project 732114750463 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=732114750463 then retry. If y
ou enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "extendedHelp": "https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=732114750463"\n   }\n  ],\n  "cod
e": 403,\n  "message": "Access Not Configured. Google+ API has not been used in project 732114750463 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=73211475046
3 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."\n }\n}\n'
```

And it worked after I enabled the API. Probably a good idea to also print out the content when status is no **200**

Thanks for all the help!

**Comment by jonparrott** [comment]
@essramos great suggestion. Thanks for being patient and walking through all the debugging steps.
