### ISSUE TITLE
cannot determine project ID (6-pubsub)

### ISSUE THREAD

**Issue by hocherie** [GoogleCloudPlatform/getting-started-python#136]
When running 'psqworker main.books_queue' in the pubsub tutorial, I have received the error "No project ID could be determined from the Cloud SDK configuration. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable". 

I have already run gcloud config before and was able to complete previous tutorials. Would anyone know how I can address this?

**Comment by Sarickshah** [comment]
Having the same issue, last week it was working just fine now getting this error as well. The project ID has been set I checked in terminal and it worked. Also checked in python and it showed the correct project name.

**Comment by philipperemy** [comment]
Same here

**Comment by bshaffer** [comment]
this tutorial has been removed
