### ISSUE TITLE
oauth2client has been deprecated

### ISSUE THREAD

**Issue by JasonMWhite** [GoogleCloudPlatform/getting-started-python#137]
https://github.com/google/oauth2client has been deprecated, replaced with [google-auth](https://google-auth.readthedocs.io/) and [oauth-lib](http://oauthlib.readthedocs.io/).

**Comment by Nathaniel-MacIver** [comment]
Jason,

     Will the tutorial docs on GCP be updated so newbies can start with these upgraded tools and save them some headaches later on?

I'm talking about this tutorial in particular: https://cloud.google.com/python/getting-started/tutorial-app

   Thanks!

**Comment by JasonMWhite** [comment]
@Nathaniel-MacIver I don't work for Google, I just created the issue when I noticed it.

**Comment by bshaffer** [comment]
the new tutorials do not use `oauth2client`. The tutorials in the `steps` branch still do, but these tutorials are going away, so we do not want to upgrade them.

Thank you for reporting this!
