### ISSUE TITLE
Session cookie too big

### ISSUE THREAD

**Issue by srianbury** [GoogleCloudPlatform/getting-started-python#159]
How can I shrink session cookies?  I am trying to authenticate users in the 4-auth directory but I cannot because the session cookie is too large.  In init.py the _request_user_info() method gets the information and stores it in session.  I tried to limit the data by only grabbing the displayName like so: profile = json.loads(content.decode('utf-8'))
    session['profile'] = {'displayName': profile['displayName']};  But this doesn't seem to change the size of the cookie at all.  Any idea how I can shrink/store the cookies?  Also I am not looking to create a centralized database to store sessions securely.

**Comment by mikeklinker129** [comment]
Seconded this as an issue. 

My full error:
`...getting-started-python/4-auth/venv/lib/python2.7/site-packages/werkzeug/wrappers.py:1116: UserWarning: The "session" cookie is too large: the value was 6583 bytes but the header required 26 extra bytes. The final size was 6609 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
  samesite=samesite`

**Comment by BlackFoxgamingstudio** [comment]
same

**Comment by jyp930** [comment]
I met a same issue and struggled with that for a few hours.
 when I change "SECRET_KEY = 'secret'" to "SECRET_KEY = 'st'", I could log in successfully. I guess encrypting with 'secret' key made too large session cookies...

**Comment by TheRoyalTnetennba** [comment]
The 4-auth folder has been removed.
