### ISSUE TITLE
Add HTTPS option in the optional-kubernetes-engine tutorial

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/getting-started-python#160]
Building Python app engine is very easy, switch to https (enterprise secure option) is very easy don't need a special tutorial.

In a perfect world, switch K8s from HTTP to HTTPS should be as easy as for App Engine, but K8s (optional-kubernetes-engine) the complexity level is much higher, requires more complex load balancer, SSL, DNS setup.

K8s is very powerful but difficult to adopt due to extra setup and difficult local complexity, with this extra example IMHO more enterprise users will be able to adopt GCP Kubernetes Engine.

**Comment by bshaffer** [comment]
There is good documentation on setting up HTTPS [here](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) and [here](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress). I do not see a benefit in making a python-specific example for this, however.
