### ISSUE TITLE
bookshelf worker gives futures error

### ISSUE THREAD

**Issue by arshak** [GoogleCloudPlatform/getting-started-python#161]
when I deploy the bookshelf-worker on GKE, the pods come up with the following error:

"22:19:21 worker.1 | AttributeError: 'StreamingPullFuture' object has no attribute 'future'

the frontend app works just fine under the same GKE cluster (same docker image, etc)

**Comment by khanduri** [comment]
@arshak .. I'm running into the same error. We're you able to get a fix for this? 
EDIT: Seems like some version issue with the google-cloud packages. I tried downgrading the `google-cloud-pubsub` package, but didn't get it working

**Comment by arshak** [comment]
@khanduri haven't been able to fix it.  GCP folks confirmed that it's an issue with this project and not a problem with GKE.  So maybe one of the contributors here will take a look.

**Comment by miketruty** [comment]
There is an updated version of psq that needs to be used with the latest code here. I've updated psq in requirements.txt to 0.7.0 for this.
