### ISSUE TITLE
problem with procfile file name

### ISSUE THREAD

**Issue by juanluisrosaramos** [GoogleCloudPlatform/getting-started-python#170]
Trying to deploy the 6-pub-sub example i found a deploy error

ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:
2018-09-06 15:00:38 [1] [ERROR] Procfile does not exist or is not a file

In this case, I changed file name from "procfile" to "Procfile" and it deployed correctly

**Comment by engelke** [comment]
Can you provide more information? Did you change the name of the file in the directory, or change the name referenced in one of the yaml files? It certainly seems that it should be procfile everywhere, not Procfile.

This sample was able to deploy for me the last time I tried it.

**Comment by engelke** [comment]
Closing this due to lack of needed details.
