### ISSUE TITLE
Connection loss during query while running model_cloudsql.py

### ISSUE THREAD

**Issue by kwokkawinghk** [GoogleCloudPlatform/getting-started-python#187]
Hi team,
When  I try to run the code in bookself\model_cloudsql.py in a window VM, it shows the error as below:

    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query') (Background on this error at: http://sqlalche.me/e/e3q8)

I have already set up the config.py and app.yaml as tutorial instructed.

How can I solve this issue and complete the task with my PostgreSQL?

Best regards,
Ka Wing

**Comment by 42force** [comment]
this means you are not connected to the sql server database 

Kind Regards,

**Comment by kwokkawinghk** [comment]
Thanks for the reply. However, I have login the goolge PostgreSQL and it shows the following when I run the code:
2019/02/06 19:13:22 Listening on 127.0.0.1:3306 for delta-basis-214516:asia-east2:ppoagentbot
2019/02/06 19:13:22 Ready for new connections
2019/02/06 19:15:43 New connection for "delta-basis-214516:asia-east2:ppoagentbot"
2019/02/06 19:21:06 Instance delta-basis-214516:asia-east2:ppoagentbot closed connection

It seems that the code connected the server before and the server closed the connection when the code is not completed.

Do you have any idea what will be the reason and how to fix it?

The flag of the SQL are as below:
 character_set_server : utf8
ft_max_word_len : 252
ft_query_expansion_limit  : 1000
group_concat_max_len  : 17179869184
innodb_lock_wait_timeout  : 1073741824
interactive_timeout  : 31536000
lock_wait_timeout : 31536000
max_allowed_packet  : 1073741824
max_heap_table_size  : 67108864
net_read_timeout  : 4294967295
net_write_timeout : 4294967295
tmp_table_size : 67108864
wait_timeout : 31536000

Many thanks,
Ka Wing

**Comment by engelke** [comment]
Please give the path of the code you're using and the URL of the web page with the instructions you're following. I'm not clear on your using a Windows VM. Is that a Compute Engine VM, something local on your own machine, or something else? Is the problem with the app when deployed to GCP (and if so, to which GCP product) or when following the 'running locally' instructions.

Thanks.

**Comment by engelke** [comment]
Closing due to lack of needed detail.
