### ISSUE TITLE
Invalid request when trying to connect after deployment

### ISSUE THREAD

**Issue by Brumor** [GoogleCloudPlatform/getting-started-python#192]
Hi,

I have followed the Bookshelf tutorial twice and still gets the same error, on my local machine I can connect fine and it works as intended, but once deployed I can't connect anymore, I click on the login button and it just shows me a blank page saying "Invalid request", looking at the browser logs it tells me : 

`oauth2callback:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)` 

And looking att the Logging in the Google Cloud console I have this error: 

`{
 httpRequest: {
  latency:  "0.002s"   
  referer:  "-"   
  remoteIp:  "145.243.200.0"   
  requestMethod:  "GET"   
  requestUrl:  "/oauth2callback?state=%7B%22csrf_token%22:%20%2226cc91a669ebae7610217aae7b8d2005d4e316c15ca937a1fd863398fa6629d6%22,%20%22return_url%22:%20%22http://python-bookshelf-app-233609.appspot.com/books/%22%7D&code=4/BgG8KhTW-YYD-HfFpUFr-zMq91FIc-HpO37CxMMW1x-sDMbKNiOtZwX1pCzDdxdHwHByc3kXLHixodWxtoSLEyI&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile"   
  responseSize:  "15"   
  status:  400   
  userAgent:  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"   
 }
 insertId:  "15moetfg3fb6nzr"  
 jsonPayload: {
  appLatencySeconds:  "0.000"   
  httpRequest: {
   protocol:  "HTTP/1.1"    
  }
  latencySeconds:  "0.002"   
  trace:  "dc2baf75b794faea437c4cf98e3ebb94"   
 }
 labels: {
  appengine.googleapis.com/instance_name:  "aef-default-20190306t151610-gh20"   
  appengine.googleapis.com/trace_id:  "dc2baf75b794faea437c4cf98e3ebb94"   
  compute.googleapis.com/resource_id:  "7209627706937469195"   
  compute.googleapis.com/resource_name:  "92d83ed0a168"   
  compute.googleapis.com/zone:  "europe-west3-a"   
 }
 logName:  "projects/python-bookshelf-app-233609/logs/appengine.googleapis.com%2Fnginx.request"  
 receiveTimestamp:  "2019-03-07T09:52:55.810033951Z"  
 resource: {
  labels: {
   module_id:  "default"    
   project_id:  "python-bookshelf-app-233609"    
   version_id:  "20190306t151610"    
  }
  type:  "gae_app"   
 }
 timestamp:  "2019-03-07T09:52:51.793Z"  
 trace:  "projects/python-bookshelf-app-233609/traces/dc2baf75b794faea437c4cf98e3ebb94"  
}`

Any idea what I could be doing wrong? Or how to fix it? It works fine on my local machine, I have set the authorized domains and Authorized redirect URIs properly (localhost and full domain, with https and http) as said in the bookshelves tutorial.

**Comment by engelke** [comment]
The bookshelf app example has several phases. I think you're referring to the one at https://cloud.google.com/python/getting-started/authenticate-users. Is that correct?

**Comment by engelke** [comment]
Closing due to lack of needed details.
