### ISSUE TITLE
'from google.cloud import store' should be 'datastore'

### ISSUE THREAD

**Issue by Belthazubel** [GoogleCloudPlatform/getting-started-python#206]
From what I'm getting from the error messages 'store' is not a thing anymore from version 0.20. Can someone confirm this? I changed it from 'store' to 'datastore' and everything seems to work.

**Comment by bshaffer** [comment]
I was unable to find `import store` in `master` or `steps`

https://github.com/GoogleCloudPlatform/getting-started-python/search?q=import+store&unscoped_q=import+store

So I believe this has already been fixed
