### ISSUE TITLE
Cannot clone git synced repo from google cloud source repository

### ISSUE THREAD

**Issue by sanealytics** [GoogleCloudPlatform/getting-started-python#242]
Hi there,
I'm trying to deploy a google cloud source repository to my deployed instance.

I'm trying (this)[https://github.com/GoogleCloudPlatform/getting-started-python/blob/steps/7-gce/gce/startup-script.sh#L45]

`git clone https://source.developers.google.com/p/$PROJECTID/r/[YOUR_REPO_NAME] /opt/app`

But it does not work. If I log into the instance and try it manually (as root), it asks me to refresh my credentials as a user.

This is git synced repo. 

Please advice

**Comment by dandhlee** [comment]
Hi there! Sorry for the late reply. 

The snippet in question now no longer exists in this repo. Please follow the updated tutorial on https://cloud.google.com/python/docs/getting-started/getting-started-on-compute-engine, let me know if you run into any issues again! :)
