### ISSUE TITLE
Folder column in the README is all 404's

### ISSUE THREAD

**Issue by YPCrumble** [GoogleCloudPlatform/getting-started-python#249]
Thanks for building this repo! I got here while googling how to work with logging using GCP and just noticed that all the links under the `Folder` column in the table are 404's.

I'd be happy to make a PR to fix but don't know where the content lives (or if it even still exists in this repo)?

**Comment by TheRoyalTnetennba** [comment]
Thanks for pointing this out. We updated/reorganized the tutorials, overlooking the README

**Comment by tmatsuo** [comment]
@TheRoyalTnetennba So can we close this now?
