### ISSUE TITLE
Bookshelf requirements dependencies broken

### ISSUE THREAD

**Issue by jose-nuno-sousa** [GoogleCloudPlatform/getting-started-python#328]
While doing the QwikLabs Fundamentals of Cloud Logging at https://google.qwiklabs.com/focuses/10911?parent=catalog I run into the issue of having conflicting versions for `google-cloud-logging` and `google-cloud-error-reporting` when running `pip3 install -r requirements.txt`

I do not know if there are specific version requirements in the project, but I've ended up changing the [requirements.txt file](https://github.com/GoogleCloudPlatform/getting-started-python/blob/main/bookshelf/requirements.txt) in the lab with the following versions and was able to proceed and finish the lab:
```
google-cloud-logging==2.2.0
google-cloud-error-reporting<=2.0
```

**Comment by tmatsuo** [comment]
@jose-nuno-sousa Thanks for the report. I'll take a look.

What were the versions of Python and OS?

Our periodic builds are passing, so I'd like to know how to reproduce the problem.

**Comment by jose-nuno-sousa** [comment]
@tmatsuo I've run it in Google Cloud Shell:
```
$ uname -a
Linux cs-638392879081-default-default-lql6f 5.4.89+ #1 SMP Thu Feb 4 19:44:58 PST 2021 x86_64 GNU/Linux
```
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

As for Python:
```
$ python --version
Python 3.7.3
```

To reproduce the issue I've followed the Qwiklabs instructions, cloned the repo, went to the bookshelf folder and from a virtualenv for python3 run the pip install of the requirements.txt:
```
git clone https://github.com/GoogleCloudPlatform/getting-started-python
cd getting-started-python/bookshelf
virtualenv -p python3 env
source env/bin/activate
pip3 install -r requirements.txt
```

It fails with the following message:
```
ERROR: Cannot install -r requirements.txt (line 5) and google-cloud-logging==2.2.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested google-cloud-logging==2.2.0
    google-cloud-error-reporting 1.1.0 depends on google-cloud-logging<2.1 and >=1.14.0
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Just to confirm:
```
$ cat requirements.txt
Flask==1.1.2
google-cloud-firestore==2.0.2
google-cloud-storage==1.36.1
google-cloud-logging==2.2.0
google-cloud-error-reporting==1.1.0
gunicorn==20.0.4
six==1.15.0
```

**Comment by tmatsuo** [comment]
@jose-nuno-sousa Thanks for the detailed info, it's very helpful.
