### ISSUE TITLE
1-hello-world Directory won't exist

### ISSUE THREAD

**Issue by rahul799** [GoogleCloudPlatform/getting-started-python#344]
I was following [this](https://cloud.google.com/python/monitor-and-debug/uptime-alert) tutorial and as per the steps mentioned, there must be a folder named **1-hello-world** inside the repo which I can't find here.
I think it's renamed to [gce](https://github.com/GoogleCloudPlatform/getting-started-python/tree/main/gce) now but the docs must be updated.

**Comment by dandhlee** [comment]
Thanks for filing this! I'll look into see what we can do to fix this.

**Comment by dandhlee** [comment]
Filed internal change to update the docs.

**Comment by dandhlee** [comment]
The page has been updated to use the new directory name. Please re-open this issue for file another issue if there's any other issues :D
