### ISSUE TITLE
Conflicting dependencies in bookshelf app

### ISSUE THREAD

**Issue by zarandr** [GoogleCloudPlatform/getting-started-python#357]
pip gives me this error:

ERROR: Cannot install -r requirements.txt (line 5) and google-cloud-logging==2.4.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested google-cloud-logging==2.4.0
    google-cloud-error-reporting 1.1.2 depends on google-cloud-logging<2.4 and >=1.14.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by dandhlee** [comment]
Thanks for bringing this up! #356 should fix this issue.
