### ISSUE TITLE
issues following tutorial

### ISSUE THREAD

**Issue by romanodev** [GoogleCloudPlatform/getting-started-python#382]
Hi, 

I am following the tutorial regarding gce. I cloned this repository and create the instance. However, it seems there is an issue with honcho (see log below). Thanks!

Jul 30 14:25:18 my-app-instance GCEMetadataScripts[731]: 2021/07/30 14:25:18 GCEMetadataScripts: startup-script: supervisorctl reread
Jul 30 14:25:19 my-app-instance GCEMetadataScripts[731]: 2021/07/30 14:25:19 GCEMetadataScripts: startup-script: pythonapp: available
Jul 30 14:25:19 my-app-instance GCEMetadataScripts[731]: 2021/07/30 14:25:19 GCEMetadataScripts: startup-script: supervisorctl update
Jul 30 14:25:19 my-app-instance supervisord[3257]: 2021-07-30 14:25:19,531 INFO spawnerr: can't find command '/opt/app/gce/env/bin/honcho'
Jul 30 14:25:19 my-app-instance GCEMetadataScripts[731]: 2021/07/30 14:25:19 GCEMetadataScripts: startup-script: pythonapp: added process group
Jul 30 14:25:19 my-app-instance GCEMetadataScripts[731]: 2021/07/30 14:25:19 GCEMetadataScripts: startup-script: # [END getting_started_gce_startup_script]
Jul 30 14:25:19 my-app-instance GCEMetadataScripts[731]: 2021/07/30 14:25:19 GCEMetadataScripts: startup-script exit status 0
Jul 30 14:25:19 my-app-instance GCEMetadataScripts[731]: 2021/07/30 14:25:19 GCEMetadataScripts: Finished running startup scripts.
Jul 30 14:25:19 my-app-instance systemd[1]: Started Google Compute Engine Startup Scripts.
Jul 30 14:25:19 my-app-instance systemd[1]: Reached target Multi-User System.
Jul 30 14:25:19 my-app-instance systemd[1]: Reached target Graphical Interface.
Jul 30 14:25:19 my-app-instance systemd[1]: Starting Update UTMP about System Runlevel Changes...
Jul 30 14:25:19 my-app-instance systemd[1]: Started Update UTMP about System Runlevel Changes.
Jul 30 14:25:19 my-app-instance systemd[1]: Startup finished in 1.551s (kernel) + 1min 29.418s (userspace) = 1min 30.969s.
Jul 30 14:25:20 my-app-instance supervisord[3257]: 2021-07-30 14:25:20,535 INFO spawnerr: can't find command '/opt/app/gce/env/bin/honcho'
Jul 30 14:25:22 my-app-instance supervisord[3257]: 2021-07-30 14:25:22,538 INFO spawnerr: can't find command '/opt/app/gce/env/bin/honcho'
Jul 30 14:25:25 my-app-instance supervisord[3257]: 2021-07-30 14:25:25,541 INFO spawnerr: can't find command '/opt/app/gce/env/bin/honcho'
Jul 30 14:25:25 my-app-instance supervisord[3257]: 2021-07-30 14:25:25,541 INFO gave up: pythonapp entered FATAL state, too many start retries too quickly

**Comment by busunkim96** [comment]
Hi @romanodev,

Thanks for filing an issue. I see the same error when I follow the instructions here: https://cloud.google.com/python/docs/getting-started/getting-started-on-compute-engine#create_and_configure_a_compute_engine_instance

I'll investigate a bit more and put together a PR to fix the tutorial.

**Comment by romanodev** [comment]
@busunkim96 , thanks. As a reference, this tutorial seems to work

https://cloud.google.com/memorystore/docs/redis/connect-redis-instance-gce#python_1

**Comment by bmalthi** [comment]
I’m getting the same error. I think the error starts because the python virtual environment isn’t being activated, and thus the honcho dependencies aren’t being installed. 

Further up in the output I get, after the step running
Source bin/activate to start the virtual environment

I get an error from that script saying
# This file must be used with “source bin/activate” *from bash*

**Comment by martinjbaker** [comment]
Is there any short term workaround for this?

**Comment by parthea** [comment]
I've confirmed that the gce tutorial is now working with the changes in #430.
