### ISSUE TITLE
Add tests and automated CI

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/getting-started-python#392]
Samples in this repository are used in several published Google Cloud tutorials.

Some directories have no tests and others have test coverage that may be too low to properly meet the [user journey testing requirement](https://g3doc.corp.google.com/company/teams/cloud-devrel/dpe/policies/testing.md?cl=head), leading to issues like #382.

**Tasks**:

- Add tests to all subdirectories.
- Check tests to make sure they sufficiently test the user journey.
- Check test infrastructure - it should ideally closely match what is in https://github.com/googlecloudplatform/python-docs-samples for easier maintainability
   - Periodic job should run nightly with flakybot enabled so we know when something breaks

CC @danoscarmike @parthea

**Comment by danoscarmike** [comment]
@busunkim96 @parthea please prioritize this one between you 🙏🏻

**Comment by parthea** [comment]
Clean up seemed more appropriate as this is technical debt. I add this to our internal audit for technical debt in GitHub repositories so it will be prioritized along with other technical debt.
