### ISSUE TITLE
Book listing in Compute Engine and Datastore not working as expected

### ISSUE THREAD

**Issue by sharifsalah** [GoogleCloudPlatform/getting-started-python#48]
Creating more than 10 books in Datastore currently results in a TypeError with the following message when listing Books: 

An internal error occurred:
character mapping must return integer, None or unicode
See logs for full stacktrace.

I've tested and observed this using the GCE sample code. I expect it would be identical in the others as the relevant code is the same across App Engine, Container Engine and Compute Engine.

To reproduce:

1 - Deploy the Compute Engine version with Datastore
2 - Create 11 Book entries
3 - Visit the URL to list the books
4 - Scroll down to the bottom and click 'More'

**Comment by jonparrott** [comment]
Thanks for reporting; I'll be looking into this shortly.
