### ISSUE TITLE
The More button is not More, it is Next

### ISSUE THREAD

**Issue by medyagh** [GoogleCloudPlatform/getting-started-python#58]
Don't mean to be a pain the neck but the more button should bring new items and add to the current showing list.
but instead it shows Next page with no option to show Previous, can we have either a Previous button or make More button a real more ? (append more to the current showing list)

**Comment by jonparrott** [comment]
Generally we prefer to avoid client-side JavaScript in these samples. I can change it to read "Next". A previous button is a bit more difficult in backends like the datastore and would require us to track cursors in the session.

**Comment by medyagh** [comment]
oh so you would have to keep track of the previous token in javascript ? googel datastore doesnt have that ? do you know where I can find an example with way more features of using datastore ? like filtering by publish date, filtering by different stuff ...I am new to google data store concepts

**Comment by jonparrott** [comment]
In MongoDB and SQL you do essentially `offset(int).limit(int)`, however, datastore uses cursors (an opaque string) to track state of the query so it can be resumed at a particular point. To be able to go backwards, you basically have to store a map of current cursor -> previous cursor. You can store it in js or memcache, it doesn't matter. It just complicates things a little.

Cloud Datastore's docs are here: https://cloud.google.com/datastore/docs/concepts/overview
If you have particular questions I may be able to help, but sometimes it's better to ask on StackOverflow.
