### ISSUE TITLE
docker build failed for optional-container-engine

### ISSUE THREAD

**Issue by ntang99** [GoogleCloudPlatform/getting-started-python#84]
ocker build -t gcr.io/google.com/cloud-solutions-gce/bookshelf  .
Sending build context to Docker daemon  89.6 kB
Step 1 : FROM gcr.io/google_appengine/python
 ---> a2511b33fad9
Step 2 : RUN virtualenv /env
 ---> Using cache
 ---> 6cef78fddb91
Step 3 : ENV VIRTUAL_ENV /env
 ---> Using cache
 ---> e2ec45b681ea
Step 4 : ENV PATH /env/bin:$PATH
 ---> Using cache
 ---> 09b07145da08
Step 5 : ADD requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 1eed1d3b4f90
Step 6 : RUN pip install -r /app/requirements.txt
 ---> Running in 1ef4285f3e93
Collecting Flask==0.11.1 (from -r /app/requirements.txt (line 1))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
Collecting gcloud==0.18.1 (from -r /app/requirements.txt (line 2))
  Downloading gcloud-0.18.1.tar.gz (435kB)
Collecting gunicorn==19.6.0 (from -r /app/requirements.txt (line 3))
  Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
Collecting oauth2client==3.0.0 (from -r /app/requirements.txt (line 4))
  Downloading oauth2client-3.0.0.tar.gz (77kB)
Collecting mock==2.0.0 (from -r /app/requirements.txt (line 5))
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
Collecting Flask-SQLAlchemy==2.1 (from -r /app/requirements.txt (line 6))
  Downloading Flask-SQLAlchemy-2.1.tar.gz (95kB)
Collecting PyMySQL==0.7.8 (from -r /app/requirements.txt (line 7))
  Downloading PyMySQL-0.7.8-py2-none-any.whl (79kB)
Collecting Flask-PyMongo==0.4.1 (from -r /app/requirements.txt (line 8))
  Downloading Flask_PyMongo-0.4.1-py2-none-any.whl
Collecting PyMongo==3.3.0 (from -r /app/requirements.txt (line 9))
  Downloading pymongo-3.3.0-cp27-cp27mu-manylinux1_x86_64.whl (339kB)
Collecting six==1.10.0 (from -r /app/requirements.txt (line 10))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting requests[security]==2.11.1 (from -r /app/requirements.txt (line 11))
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
Collecting honcho==0.7.1 (from -r /app/requirements.txt (line 12))
  Downloading honcho-0.7.1-py2.py3-none-any.whl
Collecting psq==0.4.0 (from -r /app/requirements.txt (line 13))
  Downloading psq-0.4.0-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask==0.11.1->-r /app/requirements.txt (line 1))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting Jinja2>=2.4 (from Flask==0.11.1->-r /app/requirements.txt (line 1))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Collecting Werkzeug>=0.7 (from Flask==0.11.1->-r /app/requirements.txt (line 1))
  Downloading Werkzeug-0.11.11-py2.py3-none-any.whl (306kB)
Collecting click>=2.0 (from Flask==0.11.1->-r /app/requirements.txt (line 1))
  Downloading click-6.6.tar.gz (283kB)
Collecting httplib2>=0.9.1 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading httplib2-0.9.2.zip (210kB)
Collecting googleapis-common-protos (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading googleapis-common-protos-1.3.0.tar.gz
Collecting protobuf!=3.0.0.b2.post1,>=3.0.0b2 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading protobuf-3.0.0-py2.py3-none-any.whl (342kB)
Collecting grpcio>=1.0rc1 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading grpcio-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl (4.7MB)
Collecting google-gax>=0.12.3 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading google-gax-0.12.5.tar.gz
Collecting gax-google-pubsub-v1>=0.8.0 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading gax-google-pubsub-v1-0.8.1.tar.gz
Collecting grpc-google-pubsub-v1>=0.8.0 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading grpc-google-pubsub-v1-0.8.1.tar.gz
Collecting gax-google-logging-v2>=0.8.0 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading gax-google-logging-v2-0.8.1.tar.gz
Collecting grpc-google-logging-v2>=0.8.0 (from gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Downloading grpc-google-logging-v2-0.8.1.tar.gz
Collecting pyasn1>=0.1.7 (from oauth2client==3.0.0->-r /app/requirements.txt (line 4))
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client==3.0.0->-r /app/requirements.txt (line 4))
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client==3.0.0->-r /app/requirements.txt (line 4))
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r /app/requirements.txt (line 5))
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r /app/requirements.txt (line 5))
  Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB)
Collecting SQLAlchemy>=0.7 (from Flask-SQLAlchemy==2.1->-r /app/requirements.txt (line 6))
  Downloading SQLAlchemy-1.0.15.tar.gz (4.8MB)
Collecting pyOpenSSL>=0.13; extra == "security" (from requests[security]==2.11.1->-r /app/requirements.txt (line 11))
  Downloading pyOpenSSL-16.1.0-py2.py3-none-any.whl (43kB)
Collecting ndg-httpsclient; extra == "security" (from requests[security]==2.11.1->-r /app/requirements.txt (line 11))
  Downloading ndg_httpsclient-0.4.2.tar.gz
Collecting retrying<2.0.0,>=1.0.0 (from psq==0.4.0->-r /app/requirements.txt (line 13))
  Downloading retrying-1.3.3.tar.gz
Collecting colorlog<3.0.0,>=2.6.0 (from psq==0.4.0->-r /app/requirements.txt (line 13))
  Downloading colorlog-2.7.0-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2>=2.4->Flask==0.11.1->-r /app/requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
Collecting grpc>=1.0.0 (from googleapis-common-protos->gcloud==0.18.1->-r /app/requirements.txt (line 2))
  Could not find a version that satisfies the requirement grpc>=1.0.0 (from googleapis-common-protos->gcloud==0.18.1->-r /app/requirements.txt (line 2)) (from versions: 0.3.post10, 0.3.post11, 0.3.post12, 0.3.post13, 0.3.post14, 0.3.po
st15, 0.3.post16, 0.3.post17, 0.3.post18, 0.3.post19)
No matching distribution found for grpc>=1.0.0 (from googleapis-common-protos->gcloud==0.18.1->-r /app/requirements.txt (line 2))
The command '/bin/sh -c pip install -r /app/requirements.txt' returned a non-zero code: 1

**Comment by jonparrott** [comment]
Tracking this upstream at https://github.com/GoogleCloudPlatform/gcloud-python/issues/2238
