### ISSUE TITLE
HTTP GET /books/id/delete modifies server state.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/getting-started-python#9]
According to the HTTP standard, HTTP GET requests must not modify server state.
The delete controller modifies server state with a simple GET.  This is wrong.  Bots will delete books unintentionally.  We should switch the request to a POST.

**Comment by jonparrott** [comment]
Closing for now.

**Comment by bshaffer** [comment]
This doesn't happen in the bookshelf rewrite
